In [93]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [95]:
type(a)

numpy.ndarray

In [96]:
#creating a 2d array
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [97]:
#creating a 3d array
a3 = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
print(a3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
print(a2.shape)
print(a2.ndim)
print(a2.dtype)


(2, 5)
2
int64


In [ ]:
np.arange(10)
np.arange(1,11)
np.arange(1,11,2)   

array([1, 3, 5, 7, 9])

In [100]:
np.random.randint(1,11,size = (2,3))   

array([[ 1, 10,  1],
       [ 5,  1,  4]], dtype=int32)

In [101]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])
y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)


[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [102]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [103]:
print(x@y) #matrix multipication

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [104]:
np.dot(x,y) #matrix multiplication

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [105]:
x.prod() #product of all elements of the array

np.int64(12600)

In [106]:
x.mean() #mean of all elements

np.float64(3.3333333333333335)

In [107]:
y.mean()


np.float64(3.7777777777777777)

In [108]:
x.mean(axis = 0) #column wise mean

array([4., 4., 2.])

In [109]:
y.mean(axis = 1 ) #row wise mean

array([4.        , 4.        , 3.33333333])

In [110]:
print(x.sum())
print(x.std())
print(x.var())

30
1.8257418583505538
3.3333333333333335


In [111]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25)) #1st quartile
print(np.percentile(a,50)) #median
print(np.percentile(a,75)) #3rd quartile

3.0
5.0
7.0


In [112]:
b = np.random.randint(11,100,(4,4))
print(b)

[[37 28 28 68]
 [56 13 43 87]
 [78 30 73 36]
 [92 62 89 55]]


In [113]:
print('2X8')
print(b.reshape(2,8))
print('8X2')
print(b.reshape(8,2))

2X8
[[37 28 28 68 56 13 43 87]
 [78 30 73 36 92 62 89 55]]
8X2
[[37 28]
 [28 68]
 [56 13]
 [43 87]
 [78 30]
 [73 36]
 [92 62]
 [89 55]]


In [114]:
x  = np.random.randint(1,11,(5,5))
print(x)

[[ 2  3  8  7  8]
 [ 9  5  6  2  6]
 [ 7  1  2 10  1]
 [ 8  8  2  6  6]
 [ 1  7  2  2  6]]


In [115]:
print(x[0]) #1st row
print(x[0,1]) #1st row and 2nd column's first element
print(x[-1])


print(x[:3])
print(x[3:])


[2 3 8 7 8]
3
[1 7 2 2 6]
[[ 2  3  8  7  8]
 [ 9  5  6  2  6]
 [ 7  1  2 10  1]]
[[8 8 2 6 6]
 [1 7 2 2 6]]
