In [97]:
import numpy as np

In [98]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [99]:
type(a)

numpy.ndarray

In [100]:
#creating a 2d array
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [101]:
#creating a 3d array
a3 = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
print(a3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [102]:
print(a2.shape)
print(a2.ndim)
print(a2.dtype)


(2, 5)
2
int64


In [103]:
np.arange(10)
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [104]:
np.random.randint(1,11,size = (2,3))

array([[3, 2, 2],
       [4, 4, 2]], dtype=int32)

In [105]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])
y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)


[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [106]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [107]:
print(x@y) #matrix multipication

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [108]:
np.dot(x,y) #matrix multiplication

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [109]:
x.prod() #product of all elements of the array

np.int64(12600)

In [110]:
x.mean() #mean of all elements

np.float64(3.3333333333333335)

In [111]:
y.mean()


np.float64(3.7777777777777777)

In [112]:
x.mean(axis = 0) #column wise mean

array([4., 4., 2.])

In [113]:
y.mean(axis = 1 ) #row wise mean

array([4.        , 4.        , 3.33333333])

In [114]:
print(x.sum())
print(x.std())
print(x.var())

30
1.8257418583505538
3.3333333333333335


In [115]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25)) #1st quartile
print(np.percentile(a,50)) #median
print(np.percentile(a,75)) #3rd quartile

3.0
5.0
7.0


In [116]:
b = np.random.randint(11,100,(4,4))
print(b)

[[66 66 33 92]
 [22 55 68 87]
 [23 98 59 69]
 [33 52 11 27]]


In [117]:
print('2X8')
print(b.reshape(2,8))
print('8X2')
print(b.reshape(8,2))

2X8
[[66 66 33 92 22 55 68 87]
 [23 98 59 69 33 52 11 27]]
8X2
[[66 66]
 [33 92]
 [22 55]
 [68 87]
 [23 98]
 [59 69]
 [33 52]
 [11 27]]


In [118]:
x  = np.random.randint(1,11,(5,5))
print(x)

[[ 1  9  8  1  2]
 [ 1  6  4  8  9]
 [ 4  1  7  4 10]
 [ 8  8  9 10  1]
 [ 2  3  6  1  3]]


In [119]:
print(x[0]) #1st row
print(x[0,1]) #1st row and 2nd column's first element
print(x[-1])


print(x[:3])
print(x[3:])


[1 9 8 1 2]
9
[2 3 6 1 3]
[[ 1  9  8  1  2]
 [ 1  6  4  8  9]
 [ 4  1  7  4 10]]
[[ 8  8  9 10  1]
 [ 2  3  6  1  3]]
